services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "data-set"
    volumes:
      - ./pipeline_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  ingest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: "db"
    depends_on:
      - db
